env: "local"  #development , production
storage_path: "./storage/storage.db"
app:
  alias_length: 6  #length of generated alias
  max_attempts: 10 #max amount of attempts to generate alias

http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 60s
